version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kotlin_crud_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:sistemas
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.h2.Driver
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
      SPRING_JPA_SHOW_SQL: "true"
    networks:
      - app-network
    depends_on:
      - h2db

  h2db:
    image: oscarfonts/h2:1.4.199
    container_name: h2_database
    ports:
      - "9092:9092"
      - "8082:8082"
    environment:
      H2_OPTIONS: '-tcp -tcpAllowOthers -web -webAllowOthers'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
